# Generated by Django 2.1.2 on 2018-10-28 00:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('component_type', models.CharField(choices=[('B', 'Baked'), ('I', 'Icing'), ('D', 'Decoration'), ('O', 'Other')], max_length=1)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['component_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Grocery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cost_amount', models.DecimalField(decimal_places=3, max_digits=7)),
                ('units', models.CharField(choices=[('ct', 'Count'), ('p', 'Pinch'), ('tsp', 'Teaspoon'), ('tbsp', 'Tablespoon'), ('floz', 'Fluid Ounce'), ('C', 'Cup'), ('pt', 'Pint'), ('qt', 'Quart')], max_length=4)),
                ('default_units', models.CharField(choices=[('ct', 'Count'), ('p', 'Pinch'), ('tsp', 'Teaspoon'), ('tbsp', 'Tablespoon'), ('floz', 'Fluid Ounce'), ('C', 'Cup'), ('pt', 'Pint'), ('qt', 'Quart')], max_length=4)),
                ('unit_cost', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('hash', models.CharField(default='a', max_length=33)),
            ],
            options={
                'verbose_name_plural': 'groceries',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('units', models.CharField(choices=[('ct', 'Count'), ('p', 'Pinch'), ('tsp', 'Teaspoon'), ('tbsp', 'Tablespoon'), ('floz', 'Fluid Ounce'), ('C', 'Cup'), ('pt', 'Pint'), ('qt', 'Quart')], max_length=4)),
                ('amount', models.DecimalField(decimal_places=3, max_digits=7)),
                ('for_component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bakery.Component')),
                ('for_grocery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bakery.Grocery')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=120)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('delivery_date', models.DateTimeField()),
                ('requires_delivery', models.BooleanField(default=False)),
                ('quoted_price', models.PositiveSmallIntegerField(default=0)),
                ('price_paid', models.PositiveSmallIntegerField(default=0)),
                ('postmortem_complete', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-delivery_date'],
            },
        ),
        migrations.CreateModel(
            name='OrderQuantity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('for_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bakery.Order')),
            ],
            options={
                'verbose_name_plural': 'order quantities',
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, unique=True)),
                ('time_estimate', models.DecimalField(decimal_places=3, max_digits=5)),
                ('time_actual', models.DecimalField(decimal_places=3, default=0, max_digits=5)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('price', models.PositiveSmallIntegerField(default=0)),
                ('image', models.ImageField(default='originals/default.jpg', upload_to='originals/')),
                ('image_thumb', models.CharField(default='/uploaded/thumbnails/default.jpg', max_length=300)),
                ('notes', models.TextField(blank=True, default='')),
                ('components', models.ManyToManyField(to='bakery.Component')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='orderquantity',
            name='for_recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bakery.Recipe'),
        ),
        migrations.AddField(
            model_name='order',
            name='recipes',
            field=models.ManyToManyField(through='bakery.OrderQuantity', to='bakery.Recipe'),
        ),
        migrations.AddField(
            model_name='component',
            name='groceries',
            field=models.ManyToManyField(through='bakery.Ingredient', to='bakery.Grocery'),
        ),
    ]
