# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-05 06:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='recipebases',
            new_name='recipes',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='componentbases',
            new_name='components',
        ),
    ]
