# Generated by Django 2.1.1 on 2018-10-01 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0004_auto_20180930_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='recipes',
            field=models.ManyToManyField(through='bakery.OrderQuantity', to='bakery.Recipe'),
        ),
    ]
