# Generated by Django 2.1.1 on 2018-10-26 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0005_order_recipes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='component',
            options={'ordering': ['component_type', 'name']},
        ),
        migrations.AlterModelOptions(
            name='orderquantity',
            options={'verbose_name_plural': 'order quantities'},
        ),
        migrations.AddField(
            model_name='recipe',
            name='image_thumb',
            field=models.CharField(default='/home/turbobear/mom/project/uploaded//thumbnails/default.jpg', max_length=300),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='originals/'),
        ),
    ]
