# Generated by Django 2.1.1 on 2018-10-27 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0006_auto_20181026_0151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default='originals/default.jpg', upload_to='originals/'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image_thumb',
            field=models.CharField(default='/uploaded/thumbnails/default.jpg', max_length=300),
        ),
    ]
